import { describe, expect, it } from 'vitest';
import ICAL from 'ical.js';
import { randomUUID } from 'node:crypto';
import { parseCalendar, previewImport, exportCalendar, createBackup, readBackup, remapBackup } from '../../src/domain/interchange';
import { expand } from '../../src/domain/calendar';
import { courseSchema, semesterSchema, type CalendarItem } from '../../src/shared/model';
import { item, recurrence } from '../fixtures';
const wrap=(body:string)=>`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Test//EN\r\n${body.replaceAll('\n','\r\n')}\r\nEND:VCALENDAR\r\n`;
describe('calendar interchange and full backups',()=>{
  it('imports timed, date-only, floating and VTODO data as plain text',()=>{const text=wrap('BEGIN:VEVENT\nUID:lecture-test\nSUMMARY:Lecture\\, seminar\nDTSTART;TZID=America/Toronto:20260918T090000\nDTEND;TZID=America/Toronto:20260918T100000\nDESCRIPTION:<script>alert(1)</script>\nEND:VEVENT\nBEGIN:VEVENT\nUID:holiday\nSUMMARY:Break\nDTSTART;VALUE=DATE:20261012\nDTEND;VALUE=DATE:20261017\nEND:VEVENT\nBEGIN:VTODO\nUID:todo\nSUMMARY:Read chapter\nDUE:20260920T170000\nSTATUS:COMPLETED\nEND:VTODO');const p=parseCalendar(text,{zone:'America/Toronto'});expect(p.invalid).toBe(0);expect(p.records).toHaveLength(3);const lecture=p.records[0]as CalendarItem;expect(lecture.title).toBe('Lecture, seminar');expect(lecture.notes).toBe('<script>alert(1)</script>');expect(lecture.timing).toMatchObject({start:'2026-09-18T13:00:00.000Z'});expect((p.records[1]as CalendarItem).timing).toMatchObject({endDate:'2026-10-17'});expect((p.records[2]as CalendarItem).status).toBe('completed');});
  it('preserves supported recurrence, exclusions and moved instances',()=>{const text=wrap('BEGIN:VEVENT\nUID:series\nSUMMARY:Class\nDTSTART;TZID=America/Toronto:20260907T090000\nDTEND;TZID=America/Toronto:20260907T100000\nRRULE:FREQ=WEEKLY;BYDAY=MO,WE;COUNT=6\nEXDATE;TZID=America/Toronto:20260909T090000\nEND:VEVENT\nBEGIN:VEVENT\nUID:series\nRECURRENCE-ID;TZID=America/Toronto:20260914T090000\nSUMMARY:Moved class\nDTSTART;TZID=America/Toronto:20260915T110000\nDTEND;TZID=America/Toronto:20260915T120000\nEND:VEVENT');const p=parseCalendar(text,{zone:'America/Toronto'});expect(p.invalid).toBe(0);const rows=expand(p.records,'2026-09-01','2026-10-01','America/Toronto');expect(rows).toHaveLength(5);expect(rows.find(r=>r.title==='Moved class')?.date).toBe('2026-09-15');expect(rows.some(r=>r.date==='2026-09-09')).toBe(false);});
  it('repeated import is idempotent and changed source data is explicitly flagged',()=>{const text=wrap('BEGIN:VEVENT\nUID:stable\nSUMMARY:Original\nDTSTART:20260918T130000Z\nDTEND:20260918T140000Z\nBEGIN:VALARM\nACTION:DISPLAY\nTRIGGER:-PT15M\nDESCRIPTION:Reminder\nEND:VALARM\nEND:VEVENT');const original=parseCalendar(text,{zone:'UTC'});const same=previewImport(parseCalendar(text,{zone:'UTC'}),original.records);expect(same[0].action).toBe('identical');expect(same[0].record.id).toBe(original.records[0].id);expect(previewImport(parseCalendar(text.replace('SUMMARY:Original','SUMMARY:Changed'),{zone:'UTC'}),original.records)[0].action).toBe('changed');});
  it('reports unsupported recurrence and malformed individual items without corrupting valid ones',()=>{const p=parseCalendar(wrap('BEGIN:VEVENT\nUID:hourly\nSUMMARY:Hourly\nDTSTART:20260918T130000Z\nDTEND:20260918T140000Z\nRRULE:FREQ=HOURLY;COUNT=4\nEND:VEVENT\nBEGIN:VEVENT\nUID:good\nSUMMARY:Valid\nDTSTART;VALUE=DATE:20260920\nEND:VEVENT'),{zone:'UTC'});expect(p.invalid).toBe(1);expect(p.records).toHaveLength(1);expect(p.warnings.join(' ')).toContain('finite-range');});
  it('converts unsupported hourly recurrence only for an explicit finite range',()=>{const p=parseCalendar(wrap('BEGIN:VEVENT\nUID:hourly\nSUMMARY:Hourly\nDTSTART:20260918T130000Z\nDTEND:20260918T140000Z\nRRULE:FREQ=HOURLY;COUNT=4\nEND:VEVENT'),{zone:'UTC',finiteRange:{from:'2026-09-18',to:'2026-09-18'}});expect(p.invalid).toBe(0);expect(p.records).toHaveLength(4);expect(p.records.every(r=>r.kind==='item'&&!r.recurrence)).toBe(true);expect(p.warnings.join(' ')).toContain('standalone');});
  it('exports valid iCalendar that reparses with escaped text and weekly time zones',()=>{const r=item({title:'Lab, notes; next\\week',notes:'First line\nSecond line',recurrence:recurrence({until:'2026-12-18'}),reminders:[{id:randomUUID(),minutesBefore:15}]});const text=exportCalendar([r],{zone:'America/Toronto'});expect(new ICAL.Component(ICAL.parse(text)).name).toBe('vcalendar');const p=parseCalendar(text,{zone:'America/Toronto'});expect(p.invalid).toBe(0);expect((p.records[0]as CalendarItem).title).toBe(r.title);expect((p.records[0]as CalendarItem).notes).toBe(r.notes);expect((p.records[0]as CalendarItem).recurrence?.until).toBe('2026-12-18');expect(expand(p.records,'2026-11-01','2026-11-15','America/Toronto').map(r=>r.startMs)).toEqual(expand([r],'2026-11-01','2026-11-15','America/Toronto').map(r=>r.startMs));});
  it('exports unscheduled tasks without inventing a date',()=>{const r=item({itemType:'task',timing:{mode:'unscheduled',zone:'UTC'}});const p=parseCalendar(exportCalendar([r],{zone:'UTC'}),{zone:'UTC'});expect(p.invalid).toBe(0);expect((p.records[0]as CalendarItem).timing.mode).toBe('unscheduled');});
  it('validates checksums, rejects newer backups, and remaps relationships',()=>{const semester=semesterSchema.parse({id:randomUUID(),kind:'semester',name:'Fall',startDate:'2026-09-01',endDate:'2026-12-20',zone:'UTC'});const course=courseSchema.parse({id:randomUUID(),kind:'course',name:'Algorithms',semesterId:semester.id});const assignment=item({itemType:'assignment',courseId:course.id});const study=item({itemType:'study',assignmentId:assignment.id,courseId:course.id});const original=[semester,course,assignment,study];const text=createBackup('account-a',original);expect(text).not.toContain('refreshToken');expect(readBackup(text).records).toEqual(original);const mapped=remapBackup(original);expect(new Set(mapped.map(r=>r.id)).size).toBe(4);expect((mapped[1]as any).semesterId).toBe(mapped[0].id);expect((mapped[3]as any).assignmentId).toBe(mapped[2].id);expect(()=>readBackup(text.replace('Algorithms','Forged'))).toThrow('checksum');expect(()=>readBackup(text.replace('"version": 1','"version": 2'))).toThrow();});
  it('rejects excessive files and duplicate backup identities',()=>{expect(()=>parseCalendar('x'.repeat(10*1024*1024+1),{zone:'UTC'})).toThrow('10 MiB');const r=item();expect(()=>readBackup(createBackup('test',[r,r]))).toThrow('duplicate');});
});
