import { useMemo, useState, type FormEvent } from 'react';
import { DateTime } from 'luxon';
import { Trash2, Copy, Clock3, MapPin, Repeat2, Bell, ChevronDown } from 'lucide-react';
import { addDays, localInstant, sourceDate, atDate } from '../domain/calendar';
import { itemSchema, courseSchema, semesterSchema, recurrenceSchema, makeItem, type CalendarItem, type Course, type DomainRecord, type ItemType, type Occurrence, type Preferences, type Semester, type Timing } from '../shared/model';
import { Modal, typeNames } from './ui';
type Run=(command:string,payload?:unknown,message?:string)=>Promise<any>;
const id=()=>crypto.randomUUID();
export function ItemEditor({initial,date,prefs,records,run,onClose}:{initial:CalendarItem|Occurrence|null;date:string;prefs:Preferences;records:DomainRecord[];run:Run;onClose:()=>void}){
  const occurrence=initial&&'occurrenceKey'in initial?initial:null;
  const source=initial?records.find((r):r is CalendarItem=>r.kind==='item'&&r.id===initial.id):null;
  const [scope,setScope]=useState<'one'|'series'>(occurrence?.seriesId?'one':'series');
  const clean=(value:CalendarItem|Occurrence):CalendarItem=>{const {occurrenceKey,originalDate,seriesId,startMs,endMs,date:_,endDate:__,...rest}=value as Occurrence;return rest;};
  const seed=initial?clean(initial):{...makeItem(id(),date,prefs.zone),title:'',reminders:[{id:id(),minutesBefore:prefs.defaultEventReminder}]};
  const [draft,setDraft]=useState<CalendarItem>(seed);
  const [mode,setMode]=useState<Timing['mode']>(seed.timing.mode);
  const [startDate,setStartDate]=useState(sourceDate(seed.timing)??date),[endDate,setEndDate]=useState(seed.timing.mode==='allDay'?addDays(seed.timing.endDate,-1):seed.timing.mode==='timed'?DateTime.fromISO(seed.timing.end).setZone(seed.timing.zone).toISODate()!:date);
  const [startTime,setStartTime]=useState(seed.timing.mode==='timed'?DateTime.fromISO(seed.timing.start).setZone(seed.timing.zone).toFormat('HH:mm'):seed.timing.mode==='deadline'?seed.timing.time??'':'09:00');
  const [endTime,setEndTime]=useState(seed.timing.mode==='timed'?DateTime.fromISO(seed.timing.end).setZone(seed.timing.zone).toFormat('HH:mm'):'10:00');
  const [zone,setZone]=useState(seed.timing.zone),[anchor,setAnchor]=useState('anchorTime'in seed.timing?seed.timing.anchorTime:'09:00');
  const [frequency,setFrequency]=useState(seed.recurrence?.frequency??''),[interval,setInterval]=useState(seed.recurrence?.interval??1),[days,setDays]=useState(seed.recurrence?.weekdays??[DateTime.fromISO(date).weekday]);
  const [until,setUntil]=useState(seed.recurrence?.until??''),[count,setCount]=useState(seed.recurrence?.count??10),[ending,setEnding]=useState(seed.recurrence?.until?'date':seed.recurrence?.count?'count':'never');
  const [monthlyMode,setMonthlyMode]=useState(seed.recurrence?.monthlyMode??'date'),[ordinal,setOrdinal]=useState(seed.recurrence?.ordinal??1);
  const [reminders,setReminders]=useState(seed.reminders.map(r=>r.minutesBefore).join(', '));
  const [skipBreaks,setSkipBreaks]=useState(!initial),[error,setError]=useState(''),[busy,setBusy]=useState(false),[discard,setDiscard]=useState(false),[deleting,setDeleting]=useState(false),[dirty,setDirty]=useState(false);
  const courses=records.filter((r):r is Course=>r.kind==='course'),course=courses.find(c=>c.id===draft.courseId),semester=records.find((r):r is Semester=>r.kind==='semester'&&r.id===course?.semesterId);
  const close=()=>dirty?setDiscard(true):onClose();
  function scopeChange(next:'one'|'series'){
    setScope(next);const value=next==='series'?source:occurrence;if(!value)return;setDraft(clean(value));setMode(value.timing.mode);setZone(value.timing.zone);setStartDate(sourceDate(value.timing)??date);
    if(value.timing.mode==='timed'){setStartTime(DateTime.fromISO(value.timing.start).setZone(value.timing.zone).toFormat('HH:mm'));setEndTime(DateTime.fromISO(value.timing.end).setZone(value.timing.zone).toFormat('HH:mm'));setEndDate(DateTime.fromISO(value.timing.end).setZone(value.timing.zone).toISODate()!);}
    if(value.timing.mode==='allDay')setEndDate(addDays(value.timing.endDate,-1));
  }
  async function save(event:FormEvent){event.preventDefault();setError('');setBusy(true);try{
    let timing:Timing;
    if(mode==='timed')timing={mode,start:localInstant(startDate,startTime,zone).toUTC().toISO()!,end:localInstant(endDate,endTime,zone).toUTC().toISO()!,zone};
    else if(mode==='allDay')timing={mode,startDate,endDate:addDays(endDate,1),zone,anchorTime:anchor};
    else if(mode==='deadline')timing={mode,date:startDate,time:startTime||null,zone,anchorTime:anchor};else timing={mode,zone};
    let excluded=draft.recurrence?.excludedDates??[];
    if(skipBreaks&&semester&&draft.itemType==='class'){const additional:string[]=[];for(const b of semester.breaks)for(let d=b.startDate;d<=b.endDate;d=addDays(d,1)){if(additional.length>=2000)throw new Error('Semester breaks include too many dates.');additional.push(d);}excluded=[...new Set([...excluded,...additional])];}
    const recurrence=frequency&&['timed','allDay'].includes(mode)&&!['task','assignment'].includes(draft.itemType)?recurrenceSchema.parse({frequency,interval,weekdays:days,until:ending==='date'?until:null,count:ending==='count'?count:null,monthlyMode,ordinal,excludedDates:excluded,extraDates:draft.recurrence?.extraDates??[]}):null;
    const reminderValues=reminders.trim()?reminders.split(',').map(s=>Number(s.trim())):[];
    const parsed=itemSchema.parse({...draft,timing,recurrence,reminders:reminderValues.map((minutesBefore,i)=>({id:draft.reminders[i]?.id??id(),minutesBefore}))});
    const result=scope==='one'&&occurrence?.seriesId?await run('occurrence',{seriesId:occurrence.id,date:occurrence.originalDate,action:'save',override:{title:parsed.title,timing:parsed.timing,notes:parsed.notes,location:parsed.location,reminders:parsed.reminders}},'Occurrence saved'):await run('save',parsed,initial?'Changes saved':'Added to your calendar');
    if(result)onClose();
  }catch(err){setError(err instanceof Error?err.message:'Check the details and try again.');}finally{setBusy(false);}}
  const update=(patch:Partial<CalendarItem>)=>{setDraft({...draft,...patch});setDirty(true);};
  return <><Modal title={initial?'Edit your plan':'Make a little plan'} subtitle={initial?'Keep the details up to date.':'A class, a deadline, or a little time for yourself.'} onClose={close} wide>
    <form className="editor" onSubmit={save} onChange={()=>setDirty(true)}>
      {occurrence?.seriesId&&<div className="scope-choice"><Repeat2 size={17}/><span>Apply changes to</span><select aria-label="Edit repeating item scope" value={scope} onChange={e=>scopeChange(e.target.value as any)}><option value="one">This occurrence only</option><option value="series">The entire series</option></select></div>}
      <label>Title<input autoFocus className="title-input" placeholder="What’s on your calendar?" maxLength={200} required value={draft.title} onChange={e=>update({title:e.target.value})}/></label>
      <div className="form-grid"><label>Type<select value={draft.itemType} disabled={scope==='one'&&!!occurrence?.seriesId} onChange={e=>{const type=e.target.value as ItemType;update({itemType:type});if(['class','study'].includes(type))setMode('timed');if(['assignment','task'].includes(type)){setMode('deadline');setStartTime('');setFrequency('');setReminders(String(prefs.defaultTaskReminder));}if(type==='exam')setReminders('1440, 60');}}>{Object.entries(typeNames).map(([key,name])=><option value={key} key={key}>{name}</option>)}</select></label>
      <label>Course<select value={draft.courseId??''} disabled={scope==='one'&&!!occurrence?.seriesId} onChange={e=>{update({courseId:e.target.value||null});const c=courses.find(c=>c.id===e.target.value),s=records.find((r):r is Semester=>r.kind==='semester'&&r.id===c?.semesterId);if(s&&draft.itemType==='class'&&!initial){setFrequency('WEEKLY');setEnding('date');setUntil(s.endDate);}}}><option value="">Personal / no course</option>{courses.filter(c=>!c.archived||c.id===draft.courseId).map(c=><option key={c.id} value={c.id}>{c.code?`${c.code} · `:''}{c.name}</option>)}</select></label></div>
      <fieldset><legend><Clock3 size={16}/> When</legend><div className="timing-modes">{(['timed','allDay','deadline','unscheduled']as const).filter(m=>!['class','study'].includes(draft.itemType)||m==='timed').map(m=><button key={m} type="button" className={mode===m?'selected':''} onClick={()=>{setMode(m);setDirty(true);}}>{m==='timed'?'Time block':m==='allDay'?'All day':m==='deadline'?'Deadline':'No date'}</button>)}</div>
      {mode!=='unscheduled'&&<div className="form-grid"><label>{mode==='deadline'?'Due date':'Start date'}<input type="date" required min="1900-01-01" max="2100-12-31" value={startDate} onChange={e=>{setStartDate(e.target.value);if(endDate<e.target.value)setEndDate(e.target.value);}}/></label>{mode==='timed'||mode==='deadline'?<label>{mode==='deadline'?'Due time (optional)':'Start time'}<input type="time" required={mode==='timed'} value={startTime} onChange={e=>setStartTime(e.target.value)}/></label>:<label>Last day (inclusive)<input type="date" required value={endDate} min={startDate} max="2100-12-31" onChange={e=>setEndDate(e.target.value)}/></label>}
      {mode==='timed'&&<><label>End date<input type="date" required min={startDate} max="2100-12-31" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><label>End time<input type="time" required value={endTime} onChange={e=>setEndTime(e.target.value)}/></label></>}
      </div>}
      <label>Time zone<input list="zones" value={zone} onChange={e=>setZone(e.target.value)} required/></label>
      </fieldset>
      {scope!=='one'&&['timed','allDay'].includes(mode)&&!['assignment','task'].includes(draft.itemType)&&<fieldset><legend><Repeat2 size={16}/> Repeat</legend><div className="form-grid"><label>Frequency<select value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="">Does not repeat</option><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option><option value="MONTHLY">Monthly</option><option value="YEARLY">Yearly</option></select></label>{frequency&&<label>Every<input type="number" min="1" max="52" value={interval} onChange={e=>setInterval(Number(e.target.value))}/></label>}</div>
      {frequency==='WEEKLY'&&<div className="weekday-picker">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((d,i)=><button type="button" aria-pressed={days.includes(i+1)} className={days.includes(i+1)?'selected':''} key={d} onClick={()=>setDays(days.includes(i+1)?days.filter(v=>v!==i+1):[...days,i+1])}>{d}</button>)}</div>}
      {frequency==='MONTHLY'&&<div className="form-grid"><label>Pattern<select value={monthlyMode} onChange={e=>setMonthlyMode(e.target.value as any)}><option value="date">Same date each month</option><option value="ordinal">Same weekday position</option></select></label>{monthlyMode==='ordinal'&&<label>Position<select value={ordinal} onChange={e=>setOrdinal(Number(e.target.value))}>{[1,2,3,4,5,-1].map(n=><option key={n} value={n}>{n===-1?'Last':n} {DateTime.fromISO(startDate).toFormat('cccc')}</option>)}</select></label>}</div>}
      {frequency&&<div className="form-grid"><label>Ends<select value={ending} onChange={e=>setEnding(e.target.value)}><option value="never">Never</option><option value="date">On a date</option><option value="count">After a number of occurrences</option></select></label>{ending==='date'&&<label>Last date<input type="date" required min={startDate} value={until} onChange={e=>setUntil(e.target.value)}/></label>}{ending==='count'&&<label>Occurrences<input type="number" min="1" max="999" required value={count} onChange={e=>setCount(Number(e.target.value))}/></label>}</div>}
      {frequency&&semester&&draft.itemType==='class'&&<label className="checkbox-label"><input type="checkbox" checked={skipBreaks} onChange={e=>setSkipBreaks(e.target.checked)}/> Skip breaks in {semester.name}</label>}
      </fieldset>}
      <details open={!!initial}><summary>Details & reminders <ChevronDown size={16}/></summary><div className="details-body"><label><MapPin size={15}/> Location<input placeholder="Room, building, or meeting link" maxLength={300} value={draft.location} onChange={e=>update({location:e.target.value})}/></label><label>Notes<textarea rows={3} placeholder="Anything you’ll want to remember…" maxLength={10000} value={draft.notes} onChange={e=>update({notes:e.target.value})}/></label>
      <div className="form-grid"><label>Priority<select value={draft.priority} disabled={scope==='one'&&!!occurrence?.seriesId} onChange={e=>update({priority:e.target.value as any})}><option value="normal">Normal</option><option value="high">High</option><option value="low">Low</option></select></label><label>Estimated effort (minutes)<input type="number" min="5" max="6000" value={draft.estimatedMinutes??''} disabled={scope==='one'&&!!occurrence?.seriesId} onChange={e=>update({estimatedMinutes:e.target.value?Number(e.target.value):null})}/></label></div>
      {draft.itemType==='study'&&<label>Linked assignment<select value={draft.assignmentId??''} onChange={e=>update({assignmentId:e.target.value||null})}><option value="">No linked assignment</option>{records.filter((r):r is CalendarItem=>r.kind==='item'&&r.itemType==='assignment').map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label>}
      <label><Bell size={15}/> Remind me (minutes before, separated by commas)<input value={reminders} placeholder="15, 60" onChange={e=>setReminders(e.target.value)}/></label><p className="field-help">Up to 5 reminders, from 0 to 43,200 minutes before. Leave empty for none.{mode==='unscheduled'?' Reminders activate when you add a date.':''}</p>
      {(mode==='allDay'||mode==='deadline'&&!startTime)&&<label>Reminder anchor on this date<input type="time" required value={anchor} onChange={e=>setAnchor(e.target.value)}/><span className="field-help">A 0-minute reminder is at this time; the date-only deadline is still the end of the day.</span></label>}
      </div></details>
      {error&&<p className="form-error" role="alert">{error}</p>}
      <footer className="modal-actions"><div>{initial&&<><button type="button" className="icon-button danger" title="Delete item" aria-label="Delete item" onClick={()=>setDeleting(true)}><Trash2 size={18}/></button><button type="button" className="icon-button" title="Duplicate item" aria-label="Duplicate item" onClick={async()=>{const copy={...draft,id:id(),title:`${draft.title} (copy)`,recurrence:occurrence?.seriesId?null:draft.recurrence,sourceUid:null,reminders:draft.reminders.map(r=>({...r,id:id()}))};if(await run('save',copy,'Item duplicated'))onClose();}}><Copy size={18}/></button></>}</div><div><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Saving…':initial?'Save changes':'Add to calendar'}</button></div></footer>
    </form>
  </Modal>{discard&&<Modal title="Discard your changes?" subtitle="Your unsaved changes will be lost." onClose={()=>setDiscard(false)}><div className="modal-actions"><button className="button secondary" onClick={()=>setDiscard(false)}>Keep editing</button><button className="button danger-fill" onClick={onClose}>Discard changes</button></div></Modal>}{deleting&&<Modal title={scope==='one'?'Remove this occurrence?':'Delete this item?'} subtitle={scope==='one'?'Other dates in this series will stay on your calendar.':'This removes the item and its scheduled reminders.'} onClose={()=>setDeleting(false)}><div className="modal-actions"><button className="button secondary" onClick={()=>setDeleting(false)}>Keep it</button><button className="button danger-fill" onClick={async()=>{const result=scope==='one'&&occurrence?.seriesId?await run('occurrence',{seriesId:occurrence.id,date:occurrence.originalDate,action:'cancel'},'Occurrence removed'):await run('remove',{id:draft.id},'Item deleted');if(result)onClose();}}>Delete</button></div></Modal>}</>;
}

export function CourseEditor({initial,records,run,onClose}:{initial:Course|null;records:DomainRecord[];run:Run;onClose:()=>void}){
  const [draft,setDraft]=useState(initial??courseSchema.parse({id:id(),kind:'course',name:'New course'})),[error,setError]=useState('');
  const update=(patch:Partial<Course>)=>setDraft({...draft,...patch});
  return <Modal title={initial?'Edit course':'Add a course'} subtitle="Give every class and deadline a home." onClose={onClose}><form className="editor" onSubmit={async e=>{e.preventDefault();try{if(await run('save',courseSchema.parse(draft),'Course saved'))onClose();}catch(err){setError((err as Error).message);}}}>
    <label>Course name<input autoFocus required maxLength={200} value={draft.name} onChange={e=>update({name:e.target.value})}/></label><div className="form-grid"><label>Course code<input maxLength={30} placeholder="CS 201" value={draft.code} onChange={e=>update({code:e.target.value})}/></label><label>Semester<select value={draft.semesterId??''} onChange={e=>update({semesterId:e.target.value||null})}><option value="">No semester</option>{records.filter((r):r is Semester=>r.kind==='semester').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>
    <label>Instructor<input maxLength={200} value={draft.instructor} onChange={e=>update({instructor:e.target.value})}/></label><label>Usual location<input maxLength={300} value={draft.location} onChange={e=>update({location:e.target.value})}/></label><label>Course color<input type="color" value={draft.color} onChange={e=>update({color:e.target.value})}/></label><label className="checkbox-label"><input type="checkbox" checked={draft.archived} onChange={e=>update({archived:e.target.checked})}/> Archive this course (keep its calendar items)</label>{error&&<p className="form-error">{error}</p>}<footer className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">Save course</button></footer>
  </form></Modal>;
}
export function SemesterEditor({initial,prefs,run,onClose}:{initial:Semester|null;prefs:Preferences;run:Run;onClose:()=>void}){
  const today=DateTime.now().setZone(prefs.zone);const [draft,setDraft]=useState(initial??semesterSchema.parse({id:id(),kind:'semester',name:`${today.month>=7?'Fall':'Spring'} ${today.year}`,startDate:today.startOf('month').toISODate(),endDate:today.plus({months:3}).endOf('month').toISODate(),zone:prefs.zone}));
  const [breaks,setBreaks]=useState(draft.breaks.map(b=>`${b.startDate} .. ${b.endDate}`).join('\n')),[error,setError]=useState('');
  const update=(p:Partial<Semester>)=>setDraft({...draft,...p});
  return <Modal title={initial?'Edit semester':'Add a semester'} subtitle="A clear beginning, a clear finish, and room for breaks." onClose={onClose}><form className="editor" onSubmit={async e=>{e.preventDefault();try{const parsed=semesterSchema.parse({...draft,breaks:breaks.split('\n').filter(v=>v.trim()).map(line=>{const [startDate,endDate]=line.split('..').map(v=>v.trim());return{startDate,endDate:endDate||startDate};})});if(await run('save',parsed,'Semester saved'))onClose();}catch(err){setError((err as Error).message);}}}>
    <label>Name<input autoFocus required maxLength={200} value={draft.name} onChange={e=>update({name:e.target.value})}/></label><div className="form-grid"><label>First day<input type="date" required value={draft.startDate} onChange={e=>update({startDate:e.target.value})}/></label><label>Last day<input type="date" required min={draft.startDate} value={draft.endDate} onChange={e=>update({endDate:e.target.value})}/></label></div><label>Time zone<input list="zones" required value={draft.zone} onChange={e=>update({zone:e.target.value})}/></label><label>Breaks (one date range per line)<textarea rows={3} placeholder="2026-10-12 .. 2026-10-16" value={breaks} onChange={e=>setBreaks(e.target.value)}/></label><p className="field-help">New repeating classes can skip these dates. Existing classes keep their current schedule until you edit and apply the new breaks.</p><label className="checkbox-label"><input type="checkbox" checked={draft.archived} onChange={e=>update({archived:e.target.checked})}/> Archive this semester</label>{error&&<p role="alert" className="form-error">{error}</p>}<footer className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">Save semester</button></footer>
  </form></Modal>;
}
