import { useState, type FormEvent } from 'react';
import { ArrowRight, ArrowUpRight, CalendarDays, ShieldCheck, Bell, Download, Upload, Cloud, Mail, LogOut, CheckCircle2, Settings2, FolderOpen, HardDrive, Globe2, Sparkles } from 'lucide-react';
import { DateTime } from 'luxon';
import { preferencesSchema, type Snapshot, type Preferences, type ImportPreview, type Course } from '../shared/model';
import { Modal, Logo, Empty } from './ui';
type Run=(command:string,payload?:unknown,message?:string)=>Promise<any>;
export function AuthScreen({snapshot,run}:{snapshot:Snapshot;run:Run}){
  const [mode,setMode]=useState<'signin'|'signup'|'reset'>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);await run(mode==='signin'?'auth.signIn':mode==='signup'?'auth.signUp':'auth.reset',mode==='signup'?{email,password,name}:mode==='reset'?{email}:{email,password},mode==='reset'?'If an account exists, check your email for a reset link.':undefined);setBusy(false);}
  return <div className="auth-page"><div className="auth-story"><Logo/><div className="auth-copy"><span className="eyebrow">A LITTLE MORE ORGANIZED</span><h1>Big semester.<br/><span>Clearer head.</span></h1><p>Your classes, your deadlines, your life.<br/>One calm place to make it all fit.</p><div className="auth-calendar" aria-hidden="true"><div className="mini-cal-head"><span>YOUR WEEK, AT A GLANCE</span><CalendarDays size={19}/></div><div className="mini-days">{['M','T','W','T','F'].map((d,i)=><span key={i}>{d}<b>{14+i}</b></span>)}</div><div className="sample-block one">09:00 · A fresh start</div><div className="sample-block two">Make room for a study break</div><div className="sample-block three">One thing at a time <CheckCircle2 size={15}/></div></div></div><p className="auth-foot"><ShieldCheck size={15}/> Saved locally. Synced when you’re connected.</p></div>
    <div className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><span className="eyebrow">WELCOME TO C.C. LIME</span><h2>{mode==='signup'?'Your next chapter starts here.':mode==='reset'?'Let’s get you back in.':'Good to have you here.'}</h2><p>{mode==='signup'?'Create an account to take your calendar across computers.':mode==='reset'?'We’ll send a secure password reset link.':'Sign in and pick up where you left off.'}</p>
      {mode==='signup'&&<label>Your name<input autoComplete="name" maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?"/></label>}
      <label>Email address<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@university.edu"/></label>
      {mode!=='reset'&&<label>Password<input type="password" autoComplete={mode==='signup'?'new-password':'current-password'} minLength={mode==='signup'?6:1} required value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='signup'?'At least 6 characters':'Your password'}/></label>}
      {mode==='signin'&&<button className="text-button forgot" type="button" onClick={()=>setMode('reset')}>Forgot password?</button>}
      <button className="button primary full" disabled={busy||!snapshot.configured}>{busy?'One moment…':mode==='signup'?'Create account':mode==='reset'?'Send reset link':'Sign in'}<ArrowRight size={17}/></button>
      {mode!=='reset'&&<><div className="divider-label"><span>or</span></div><button className="button google full" type="button" disabled={busy||!snapshot.googleConfigured} onClick={async()=>{setBusy(true);await run('auth.google');setBusy(false);}}><span className="google-g">G</span> Continue with Google</button>{!snapshot.googleConfigured&&<p className="field-help center">Google desktop sign-in is awaiting its final client configuration.</p>}</>}
      {busy&&<button type="button" className="text-button" onClick={()=>run('auth.cancel')}>Cancel Google sign-in</button>}
      <p className="auth-switch">{mode==='signin'?'New here? ':mode==='signup'?'Already have an account? ':''}<button type="button" className="text-button" onClick={()=>setMode(mode==='signin'?'signup':'signin')}>{mode==='signin'?'Create an account':'Back to sign in'}</button></p>
      <div className="preview-note"><button type="button" className="text-button" onClick={()=>run('localPreview')}>Explore a local calendar <ArrowUpRight size={14}/></button><span>Saved on this PC. Cloud sync starts after sign-in.</span></div>
    </form></div></div>;
}
export function Onboarding({prefs,snapshot,run,onClose}:{prefs:Preferences;snapshot:Snapshot;run:Run;onClose:()=>void}){
  const [zone,setZone]=useState(prefs.zone),[weekStart,setWeekStart]=useState(prefs.weekStart),[notifications,setNotifications]=useState(snapshot.device.notifications),[startup,setStartup]=useState(false),[busy,setBusy]=useState(false);
  return <Modal title="Make yourself at home." subtitle="A few small choices for your calendar. You can change these anytime." onClose={onClose}><form className="editor" onSubmit={async e=>{e.preventDefault();setBusy(true);const saved=await run('save',{...prefs,zone,weekStart});if(saved&&await run('device',{notifications,startAtLogin:startup,onboardingDone:true}))onClose();setBusy(false);}}><label>Your calendar time zone<input list="zones" required value={zone} onChange={e=>setZone(e.target.value)}/></label><label>First day of the week<select value={weekStart} onChange={e=>setWeekStart(Number(e.target.value) as 1|7)}><option value={1}>Monday</option><option value={7}>Sunday</option></select></label><label className="toggle-card"><span><b>Desktop reminders</b><small>Popups while C.C. Lime is open or in your tray.</small></span><input type="checkbox" checked={notifications} onChange={e=>setNotifications(e.target.checked)}/></label><label className="toggle-card"><span><b>Start with Windows</b><small>Open quietly in the background when you sign in.</small></span><input type="checkbox" checked={startup} onChange={e=>setStartup(e.target.checked)}/></label><p className="field-help">Sleeping or shut-down laptops can’t show reminders. Missed reminders appear when you return.</p><footer className="modal-actions"><button type="button" className="button secondary" onClick={async()=>{await run('device',{onboardingDone:true});onClose();}}>Use defaults</button><button className="button primary" disabled={busy}>Let’s get organized <ArrowRight size={16}/></button></footer></form></Modal>;
}
export function SettingsScreen({snapshot,prefs,run,openData}:{snapshot:Snapshot&{dataPath?:string;remembered?:boolean;startup?:{enabled:boolean}};prefs:Preferences;run:Run;openData:(mode:'import'|'export'|'restore')=>void}){
  const [zone,setZone]=useState(prefs.zone),[linkPassword,setLinkPassword]=useState(''),[signOut,setSignOut]=useState(false);
  const savePrefs=(patch:Partial<Preferences>)=>run('save',{...prefs,...patch},'Calendar preferences saved');
  return <div className="settings-grid"><section className="settings-card"><h2><Settings2 size={18}/> Calendar</h2><label>Calendar time zone<div className="input-action"><input list="zones" value={zone} onChange={e=>setZone(e.target.value)}/><button className="button secondary" onClick={()=>savePrefs({zone})}>Apply</button></div></label><p className="field-help">Timed events keep their original instant. All-day dates stay pinned to their date.</p><div className="form-grid"><label>Week starts on<select value={prefs.weekStart} onChange={e=>savePrefs({weekStart:Number(e.target.value)as 1|7})}><option value={1}>Monday</option><option value={7}>Sunday</option></select></label><label>Time format<select value={prefs.timeFormat} onChange={e=>savePrefs({timeFormat:e.target.value as any})}><option value="12">12-hour (2:30 PM)</option><option value="24">24-hour (14:30)</option></select></label></div><div className="form-grid"><label>New event reminder (minutes)<input type="number" min="0" max="43200" defaultValue={prefs.defaultEventReminder} onBlur={e=>{if(Number(e.target.value)!==prefs.defaultEventReminder)void savePrefs({defaultEventReminder:Number(e.target.value)});}}/></label><label>New task reminder (minutes)<input type="number" min="0" max="43200" defaultValue={prefs.defaultTaskReminder} onBlur={e=>{if(Number(e.target.value)!==prefs.defaultTaskReminder)void savePrefs({defaultTaskReminder:Number(e.target.value)});}}/></label></div></section>
    <section className="settings-card"><h2><Bell size={18}/> Reminders on this computer</h2><label className="toggle-card"><span><b>Desktop reminders</b><small>Keep a history in your reminder inbox.</small></span><input type="checkbox" checked={snapshot.device.notifications} onChange={e=>run('device',{notifications:e.target.checked})}/></label><label className="toggle-card"><span><b>Keep details private</b><small>Hide titles in desktop popups.</small></span><input type="checkbox" checked={snapshot.device.privacy} onChange={e=>run('device',{privacy:e.target.checked})}/></label><div className="form-grid"><label>Quiet hours start<input type="time" value={snapshot.device.quietStart??''} onChange={e=>run('device',{quietStart:e.target.value||null})}/></label><label>Quiet hours end<input type="time" value={snapshot.device.quietEnd??''} onChange={e=>run('device',{quietEnd:e.target.value||null})}/></label></div><p className="field-help">Leave blank for no quiet hours. Windows Do Not Disturb may also hide banners.</p><button className="button secondary" onClick={()=>run('testNotification',undefined,'Test reminder submitted to Windows. Check your notification settings if no banner appears.')}>Send a test reminder</button></section>
    <section className="settings-card"><h2><Cloud size={18}/> Account & sync</h2><p><b>{snapshot.session?.email??'Local calendar preview'}</b></p><p className="muted">{snapshot.sync.message}</p>{snapshot.session&&<p className="field-help">Session {snapshot.remembered?'remembered with Windows encryption.':'is not remembered on this computer.'}</p>}<p className="field-help">Last synced: {snapshot.sync.lastSynced?DateTime.fromISO(snapshot.sync.lastSynced).toFormat('MMM d, h:mm a'):'Not yet'} · {snapshot.sync.pending} pending</p><div className="button-row"><button className="button secondary" onClick={()=>run('sync')}>Sync now</button>{snapshot.session&&!snapshot.session.verified&&<button className="button secondary" onClick={()=>run('auth.verify',undefined,'Verification email sent.')}>Resend verification</button>}</div>
      {snapshot.session&&!snapshot.session.providers.includes('google.com')&&<button className="text-button" disabled={!snapshot.googleConfigured} onClick={()=>run('auth.google',{link:true},'Google linked to your account')}>Link Google sign-in</button>}
      {snapshot.session&&!snapshot.session.providers.includes('password')&&<label>Add email/password sign-in<div className="input-action"><input type="password" minLength={6} value={linkPassword} onChange={e=>setLinkPassword(e.target.value)} autoComplete="new-password"/><button className="button secondary" onClick={async()=>{if(await run('auth.linkPassword',{password:linkPassword},'Password sign-in added'))setLinkPassword('');}}>Add</button></div></label>}
      <button className="text-button" onClick={()=>setSignOut(true)}><LogOut size={15}/>{snapshot.session?'Sign out':'Return to sign-in'}</button>
    </section>
    <section className="settings-card"><h2><HardDrive size={18}/> Files & backups</h2><div className="settings-actions"><button onClick={()=>openData('import')}><Upload size={18}/><span><b>Import a calendar</b><small>Preview an .ics file before adding it</small></span><ArrowUpRight size={15}/></button><button onClick={()=>openData('export')}><Download size={18}/><span><b>Export your calendar</b><small>A calendar file for other apps</small></span><ArrowUpRight size={15}/></button><button onClick={()=>run('backup',undefined,'Full backup saved')}><ShieldCheck size={18}/><span><b>Save a full backup</b><small>All courses, dates, and completion history</small></span><ArrowUpRight size={15}/></button><button onClick={()=>openData('restore')}><Upload size={18}/><span><b>Restore a full backup</b><small>Review first and preserve existing work</small></span><ArrowUpRight size={15}/></button></div><p className="field-help">Backup files contain private calendar data and are not encrypted. Passwords, sign-in tokens, and reminder history are excluded.</p></section>
    <section className="settings-card"><h2><Globe2 size={18}/> App behavior</h2><label className="toggle-card"><span><b>Close to the system tray</b><small>Keep reminders running when the window closes.</small></span><input type="checkbox" checked={snapshot.device.closeToTray} onChange={e=>run('device',{closeToTray:e.target.checked})}/></label><label className="toggle-card"><span><b>Start with Windows</b><small>Open quietly after signing into Windows.</small></span><input type="checkbox" checked={snapshot.device.startAtLogin} onChange={e=>run('device',{startAtLogin:e.target.checked})}/></label>{snapshot.device.startAtLogin&&!snapshot.startup?.enabled&&<p className="form-error">Windows startup is disabled. Check Settings → Apps → Startup.</p>}<p className="field-help">Ctrl+N adds an item · Ctrl+F searches · Ctrl+T goes to today. Use arrow keys and Enter to explore the calendar.</p></section>
    <section className="settings-card"><h2><CalendarDays size={18}/> About C.C. Lime</h2><p>Your semester, a little more in order.</p><p className="muted">Version {snapshot.version} · Windows desktop</p><p className="field-help">Local calendars are stored on this computer. Cloud data is accessible to the Firebase project owner. There are no ads, analytics, or automatic uploads of diagnostics.</p><div className="button-row"><button className="button secondary" onClick={()=>run('dataFolder')}><FolderOpen size={15}/> Open data folder</button><button className="button secondary" onClick={()=>run('diagnostics',undefined,'Diagnostics saved')}>Save diagnostics</button></div><p className="field-help">Diagnostics include app/OS versions, record counts, sync state, and operation counts. They exclude calendar text and account credentials.</p></section>
    {signOut&&<Modal title="Sign out of this calendar?" subtitle={`${snapshot.sync.pending?`${snapshot.sync.pending} changes are still waiting to sync. `:''}Saved data stays on this computer. Reminders stop until you sign in again.`} onClose={()=>setSignOut(false)}><div className="modal-actions"><button className="button secondary" onClick={()=>setSignOut(false)}>Stay here</button><button className="button primary" onClick={()=>run('auth.signOut')}>Sign out</button></div></Modal>}
  </div>;
}
export function DataDialog({mode,prefs,courses,run,onClose}:{mode:'import'|'export'|'restore';prefs:Preferences;courses:Course[];run:Run;onClose:()=>void}){
  const [zone,setZone]=useState(prefs.zone),[finite,setFinite]=useState(false),[from,setFrom]=useState(DateTime.now().startOf('month').toISODate()!),[to,setTo]=useState(DateTime.now().plus({months:3}).endOf('month').toISODate()!);
  const [preview,setPreview]=useState<ImportPreview|null>(null),[restore,setRestore]=useState<any>(null),[includeChanged,setIncludeChanged]=useState(false),[selectedCourses,setSelectedCourses]=useState<string[]>([]),[busy,setBusy]=useState(false),[restoreMode,setRestoreMode]=useState('copies');
  const act=async()=>{setBusy(true);try{if(mode==='import'){if(preview){const r=await run('import.commit',{token:preview.token,includeChanged},'Calendar imported');if(r)onClose();}else setPreview(await run('import.preview',{zone,...(finite?{finiteRange:{from,to}}:{})}));}else if(mode==='export'){if(await run('export',{courses:selectedCourses,...(finite?{range:{from,to}}:{})},'Calendar exported'))onClose();}else if(restore){if(await run('restore.commit',{token:restore.token,mode:restoreMode},'Backup restored'))onClose();}else setRestore(await run('restore.preview'));}finally{setBusy(false);}};
  return <Modal title={mode==='import'?'Bring your calendar along':mode==='export'?'Take your calendar with you':'Restore a calendar backup'} subtitle={mode==='import'?'Preview every change before it reaches your calendar.':mode==='export'?'Calendar export works with other calendar apps. Use Full backup for complete recovery.':'Existing work is preserved. You’ll review the backup before applying it.'} onClose={()=>{void run('import.cancel');onClose();}} wide>
    <div className="editor">{mode==='import'&&!preview&&<label>Time zone for floating dates<input list="zones" value={zone} onChange={e=>setZone(e.target.value)}/></label>}
    {mode!=='restore'&&!preview&&<><label className="checkbox-label"><input type="checkbox" checked={finite} onChange={e=>setFinite(e.target.checked)}/>{mode==='import'?'Convert unsupported repeating events within a finite date range':'Export a date range as standalone occurrences'}</label>{finite&&<div className="form-grid"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></div>}</>}
    {mode==='export'&&courses.length>0&&<fieldset><legend>Courses (leave unchecked for everything)</legend>{courses.map(c=><label key={c.id} className="checkbox-label"><input type="checkbox" checked={selectedCourses.includes(c.id)} onChange={e=>setSelectedCourses(e.target.checked?[...selectedCourses,c.id]:selectedCourses.filter(id=>id!==c.id))}/>{c.code||c.name}</label>)}</fieldset>}
    {preview&&<><div className="import-counts"><span><b>{preview.candidates.filter(c=>c.action==='new').length}</b> new</span><span><b>{preview.candidates.filter(c=>c.action==='identical').length}</b> unchanged</span><span><b>{preview.candidates.filter(c=>c.action==='changed').length}</b> changed</span><span><b>{preview.invalid}</b> skipped</span></div><p className="muted">{preview.filename}</p>{preview.warnings.length>0&&<details open><summary>{preview.warnings.length} import notes</summary><ul className="import-warnings">{preview.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>}<div className="import-preview-list">{preview.candidates.slice(0,200).map((c,i)=><div key={i}><span>{c.record.kind==='item'?c.record.title:`Occurrence edit · ${c.record.kind==='exception'?c.record.originalDate:''}`}</span><span className={`badge ${c.action}`}>{c.action}</span></div>)}</div>{preview.candidates.length>200&&<p className="field-help">Showing the first 200 of {preview.candidates.length} records.</p>}<label className="checkbox-label"><input type="checkbox" checked={includeChanged} onChange={e=>setIncludeChanged(e.target.checked)}/> Also replace changed imported items with the file’s version</label><p className="field-help">Unchanged duplicates are skipped. Existing edits are kept unless you choose to replace changed items.</p></>}
    {restore&&<><div className="restore-summary"><ShieldCheck size={28}/><div><h3>{restore.count} records ready to restore</h3><p>{restore.filename} · {DateTime.fromISO(restore.createdAt).toFormat('MMM d, yyyy')}</p></div></div><label>Restore method<select value={restoreMode} onChange={e=>setRestoreMode(e.target.value)}><option value="copies">Separate copies with new identities</option>{!restore.foreign&&<option value="merge">Merge missing / identical items only</option>}</select></label><p className="field-help">{restore.foreign?'This backup belongs to another account. IDs and relationships will be remapped.':'Copies preserve both the current and backed-up versions. Merge refuses to overwrite differing items.'}</p></>}
    <footer className="modal-actions"><button className="button secondary" onClick={()=>{void run('import.cancel');onClose();}}>{busy?'Cancel processing':'Cancel'}</button><button className="button primary" disabled={busy} onClick={act}>{busy?'Working…':mode==='import'?preview?'Import selected changes':'Choose .ics file':mode==='export'?'Export calendar':restore?'Restore backup':'Choose backup'}</button></footer></div>
  </Modal>;
}
